import HeaderLayout from "./header"
import FooterLayout from "./footer"
import '../../public/css/global.css'

export const metadata = {
  title: 'Nathalie Diaz Assistanat',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <HeaderLayout/>
        {children}
        <FooterLayout/>
      </body>
    </html>
  )
}
