import HeaderLayout from "./templates/header"
import FooterLayout from "./templates/footer"
import '../../public/css/global.css'
import styles from '../../public/css/background.module.css'

export const metadata = {
  title: 'Nathalie Diaz Assistanat',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <HeaderLayout/>
          <main className={styles.background}>
            {children}
          </main>
        <FooterLayout/>
      </body>
    </html>
  )
}
